apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: fleet-example
spec:
  replicas: 0
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          container: simple-game-server
          containerPort: 7777
          protocol: TCP
        - name: HTTP
          portPolicy: Dynamic
          container: simple-game-server
          containerPort: 7778
          protocol: TCP
      health:
        disabled: false
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      template:
        spec:
          containers:
          - name: simple-game-server
            image: arzmetaacr.azurecr.io/gameserver_test:agones_v0.<version>
          nodeSelector:
            agentpool: workers