apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: fleet
spec:
  replicas: 0
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          container: game-server
          containerPort: 7777
          protocol: TCP
        - name: HTTP
          portPolicy: Dynamic
          container: game-server
          containerPort: 7778
          protocol: TCP
      health:
        disabled: false
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      template:
        metadata:
          matchLabels:
            mode : <mode>
        spec:
          containers:
          - name: game-server
            image: arzmetaacr.azurecr.io/gameserver_test:agones_v0.<version>
            env:
            - name: CLOSE_ON_EMPTY
              value: '1'
            - name: CLOSE_ON_IDLE
              value: '1'
            - name: DELAY_SEND
              value: '0'
            - name: DELAY_SEND_INTERVAL
              value: '200'
            - name: MODE
              value: <mode>
            volumeMounts:
            - name: coredump
              mountPath: /mnt/coredump
          volumes:
          - name: coredump
            persistentVolumeClaim:
              claimName: core-dump-pvc
          nodeSelector:
            agentpool: workers