apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler
spec:
  fleetName: fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 3
      maxReplicas: 200
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: 10