apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-server-allocator
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: game-server-allocator-role
  namespace: default
rules:
- apiGroups: ["allocation.agones.dev"]
  resources: ["gameserverallocations"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-server-allocator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: game-server-allocator
  namespace: default
roleRef:
  kind: Role
  name: game-server-allocator-role
  apiGroup: rbac.authorization.k8s.io
